// POST Action
export const POST_USER_REQUEST = "POST_USER_REQUEST"
export const POST_USER_SUCCESS = "POST_USER_SUCCESS"
export const POST_USER_FAILURE = "POST_USER_FAILURE"

// GET Action
export const GET_USER_REQUEST = "GET_USER_REQUEST"
export const GET_USER_SUCCESS = "GET_USER_SUCCESS"
export const GET_USER_FAILURE = "GET_USER_FAILURE"

export const GET_USER_LIST_REQUEST = "GET_USER_LIST_REQUEST"
export const GET_USER_LIST_SUCCESS = "GET_USER_LIST_SUCCESS"
export const GET_USER_LIST_FAILURE = "GET_USER_LIST_FAILURE"

// DELETE Action
export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST"
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS"
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE"

